FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 6767

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "6767", "--reload", "--reload-dir", "/app", "--app-dir", "/app"]
